# Your worker name hello-world-worker.your-subdomain.workers.dev
name = "hello-world-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "ASSETS", id = "e5c092e9c8ff42c2bef41dd364423322", preview_id = "e5c092e9c8ff42c2bef41dd364423322" }
]

[site]
bucket = "./src"

# [triggers]
# crons = ["0 0 * * *"]
