# Your worker name hello-world-worker.your-subdomain.workers.dev
name = "hello-world-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MY_KV_NAMESPACE"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

# [triggers]
# crons = ["0 0 * * *"]
