# Your worker name hello-world-worker.your-subdomain.workers.dev
name = "hello-world-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./src"

# [triggers]
# crons = ["0 0 * * *"]
